"""remove has_folder and is_initial from acor group model

Revision ID: 082e939af522
Revises: ba8f1622e99e
Create Date: 2025-11-07 21:19:38.014183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '082e939af522'
down_revision: Union[str, None] = 'ba8f1622e99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_actor_group', 'has_folder')
    op.drop_column('tab_actor_group', 'is_initial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor_group', sa.Column('is_initial', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('tab_actor_group', sa.Column('has_folder', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
