"""add column post_id_str

Revision ID: 08b7cd1b6988
Revises: 689d574a0bcc
Create Date: 2025-05-20 23:13:25.695210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08b7cd1b6988'
down_revision: Union[str, None] = '689d574a0bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_post', sa.Column('post_id_str', sa.String(length=20), nullable=False))
    op.create_index('idx_post_id_str', 'tab_post', [sa.literal_column('post_id_str(8)')], unique=False)
    op.alter_column('tab_res_url', 'hash_binary',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_res_url', 'hash_binary',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.drop_index('idx_post_id_str', table_name='tab_post')
    op.drop_column('tab_post', 'post_id_str')
    # ### end Alembic commands ###
