"""add_last_log_time_to_actor

Revision ID: 0cd13cfa83fe
Revises: dce9abcbb444
Create Date: 2026-02-06 15:39:34.245519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd13cfa83fe'
down_revision: Union[str, None] = 'dce9abcbb444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('last_log_time', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tab_actor_last_log_time'), 'tab_actor', ['last_log_time'], unique=False)
    # ### end Alembic commands ###

    # --- BEGIN DATA MIGRATION ---
    print("Backfilling last_log_time...")
    op.execute("""
        UPDATE tab_actor
        JOIN (
            SELECT
                actor_id,
                MAX(log_time) AS max_log_time
            FROM tab_log
            GROUP BY actor_id
        ) AS subquery ON tab_actor.actor_id = subquery.actor_id
        SET tab_actor.last_log_time = subquery.max_log_time
    """)
    
    print("Data migration completed.")
    # --- END DATA MIGRATION ---

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_actor_last_log_time'), table_name='tab_actor')
    op.drop_column('tab_actor', 'last_log_time')
    # ### end Alembic commands ###
