"""change icon_hash tostring

Revision ID: 2439885ab3be
Revises: d3241805c36a
Create Date: 2025-11-12 21:14:25.188941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2439885ab3be'
down_revision: Union[str, None] = 'd3241805c36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_actor', 'icon_hash',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_actor', 'icon_hash',
               existing_type=sa.String(length=16),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
