"""add icon_hash_compared to actor model

Revision ID: 3c448946d5d2
Revises: 2439885ab3be
Create Date: 2025-11-14 14:26:08.940183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c448946d5d2'
down_revision: Union[str, None] = '2439885ab3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('icon_hash_compared', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_actor', 'icon_hash_compared')
    # ### end Alembic commands ###
