"""init post_id_str

Revision ID: 44a4ed2d4759
Revises: 08b7cd1b6988
Create Date: 2025-05-20 23:14:57.675466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '44a4ed2d4759'
down_revision: Union[str, None] = '08b7cd1b6988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_id_str', table_name='tab_post', mysql_length={'post_id_str': 8})
    op.create_index('idx_post_id_str', 'tab_post', [sa.literal_column('post_id_str(8)')], unique=False)
    op.alter_column('tab_res_url', 'hash_binary',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###

    # 更新现有数据
    op.execute("""
        UPDATE tab_post 
        SET post_id_str = CAST(post_id AS CHAR)
        WHERE post_id_str = ''
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_res_url', 'hash_binary',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.drop_index('idx_post_id_str', table_name='tab_post')
    op.create_index('idx_post_id_str', 'tab_post', ['post_id_str'], unique=False, mysql_length={'post_id_str': 8})
    # ### end Alembic commands ###
