"""add scan version to actor and post

Revision ID: 4c4be6a03d55
Revises: 7f59d9e2d51d
Create Date: 2025-12-03 13:08:30.678707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4be6a03d55'
down_revision: Union[str, None] = '7f59d9e2d51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('post_scan_version', sa.Integer(), nullable=False))
    op.add_column('tab_post', sa.Column('scan_version', sa.Integer(), nullable=False))
    op.create_index('idx_actor_id_scan_version', 'tab_post', ['actor_id', 'scan_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_actor_id_scan_version', table_name='tab_post')
    op.drop_column('tab_post', 'scan_version')
    op.drop_column('tab_actor', 'post_scan_version')
    # ### end Alembic commands ###
