"""actor file info

Revision ID: 5fd22a46fcfe
Revises: b9a87a00d3be
Create Date: 2025-05-26 14:46:13.635779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from Consts import ResType
from Models.BaseModel import IntEnum

# revision identifiers, used by Alembic.
revision: str = '5fd22a46fcfe'
down_revision: Union[str, None] = 'b9a87a00d3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_actor_file_info',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('res_state', IntEnum(ResType), nullable=False),
    sa.Column('res_size', sa.BigInteger(), nullable=False),
    sa.Column('img_count', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['tab_actor.actor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'res_state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_actor_file_info')
    # ### end Alembic commands ###
