"""fix db2

Revision ID: 689d574a0bcc
Revises: e2e6d183e9f1
Create Date: 2025-05-20 23:08:28.072901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '689d574a0bcc'
down_revision: Union[str, None] = 'e2e6d183e9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_res_url', 'hash_binary',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_res_url', 'hash_binary',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
