"""add has_thumbnail to post model 

Revision ID: 719ec9e96a87
Revises: af32fb0f41f3
Create Date: 2025-10-07 01:14:09.653382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719ec9e96a87'
down_revision: Union[str, None] = 'af32fb0f41f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_post', sa.Column('has_thumbnail', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_post', 'has_thumbnail')
    # ### end Alembic commands ###
