"""add has_comment

Revision ID: 73a5c745c822
Revises: 4d19a2e41276
Create Date: 2025-09-02 12:38:04.689937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a5c745c822'
down_revision: Union[str, None] = '4d19a2e41276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column(
        'has_comment', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_tab_actor_has_comment'),
                    'tab_actor', ['has_comment'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
    UPDATE tab_actor SET has_comment = 1 WHERE comment IS NOT NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_actor_has_comment'), table_name='tab_actor')
    op.drop_column('tab_actor', 'has_comment')
    # ### end Alembic commands ###
