"""add has_missing_posts  to actor

Revision ID: 77e12193df1f
Revises: 4c4be6a03d55
Create Date: 2025-12-04 12:39:11.240166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e12193df1f'
down_revision: Union[str, None] = '4c4be6a03d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('has_missing_posts', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_tab_actor_has_missing_posts'), 'tab_actor', ['has_missing_posts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_actor_has_missing_posts'), table_name='tab_actor')
    op.drop_column('tab_actor', 'has_missing_posts')
    # ### end Alembic commands ###
