"""update notice indices

Revision ID: 7f59d9e2d51d
Revises: 3c448946d5d2
Create Date: 2025-11-14 15:50:01.306830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f59d9e2d51d'
down_revision: Union[str, None] = '3c448946d5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_notice_type_checksum'), table_name='tab_notice')
    op.create_index('idx_notice_type_deleted', 'tab_notice', ['notice_type', 'deleted'], unique=False)
    op.create_index(op.f('ix_tab_notice_notice_checksum'), 'tab_notice', ['notice_checksum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_notice_notice_checksum'), table_name='tab_notice')
    op.drop_index('idx_notice_type_deleted', table_name='tab_notice')
    op.create_index(op.f('idx_notice_type_checksum'), 'tab_notice', ['notice_type', 'notice_checksum'], unique=False)
    # ### end Alembic commands ###
