"""add_actor_timestamps

Revision ID: 84f5c342a5ff
Revises: ff14adbcd044
Create Date: 2025-08-12 14:04:19.191831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from Consts import ActorLogType

# revision identifiers, used by Alembic.
revision: str = '84f5c342a5ff'
down_revision: Union[str, None] = 'ff14adbcd044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tab_actor', sa.Column('last_post_fetch_time', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('tab_actor', sa.Column('last_res_download_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # --- BEGIN DATA MIGRATION (MySQL Syntax) ---

    print("Backfilling last_post_fetch_time for MySQL...")
    op.execute(f"""
        UPDATE tab_actor
        JOIN (
            SELECT
                actor_id,
                MAX(log_time) AS max_log_time
            FROM tab_log
            WHERE log_type = {ActorLogType.PostCount.value}
            GROUP BY actor_id
        ) AS subquery ON tab_actor.actor_id = subquery.actor_id
        SET tab_actor.last_post_fetch_time = subquery.max_log_time
    """)

    print("Backfilling last_res_download_time for MySQL...")
    op.execute(f"""
        UPDATE tab_actor
        JOIN (
            SELECT
                actor_id,
                MAX(log_time) AS max_log_time
            FROM tab_log
            GROUP BY actor_id
        ) AS subquery ON tab_actor.actor_id = subquery.actor_id
        SET tab_actor.last_res_download_time = subquery.max_log_time
    """)

    print("Data migration completed.")
    # --- END DATA MIGRATION ---

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_actor', 'last_res_download_time')
    op.drop_column('tab_actor', 'last_post_fetch_time')
    # ### end Alembic commands ###
