"""fix res width height duration

Revision ID: 94542a1beaf0
Revises: bb0f7750b8b5
Create Date: 2025-06-23 14:13:26.490834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94542a1beaf0'
down_revision: Union[str, None] = 'bb0f7750b8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_post_id_res_index', 'tab_res', ['post_id', 'res_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_id_res_index', table_name='tab_res')
    # ### end Alembic commands ###
