"""new actor list model

Revision ID: 98c2dbe36c5f
Revises: e9c4df1c277d
Create Date: 2025-07-15 16:20:04.816182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c2dbe36c5f'
down_revision: Union[str, None] = 'e9c4df1c277d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_actor_list',
    sa.Column('list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_name', sa.String(length=30), nullable=False),
    sa.Column('list_desc', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('list_id'),
    sa.UniqueConstraint('list_name')
    )
    op.create_table('rel_actor_list',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('list_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['tab_actor.actor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['tab_actor_list.list_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'list_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_actor_list')
    op.drop_table('tab_actor_list')
    # ### end Alembic commands ###
