"""update fetch time for actor

Revision ID: ace9746fb9d8
Revises: 77e12193df1f
Create Date: 2025-12-22 20:04:21.069496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ace9746fb9d8'
down_revision: Union[str, None] = '77e12193df1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('last_fetch_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_tab_actor_last_post_fetch_time'), table_name='tab_actor')
    op.drop_index(op.f('ix_tab_actor_last_res_download_time'), table_name='tab_actor')
    op.create_index(op.f('ix_tab_actor_last_fetch_time'), 'tab_actor', ['last_fetch_time'], unique=False)
    op.drop_column('tab_actor', 'last_res_download_time')
    op.drop_column('tab_actor', 'last_post_fetch_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('last_post_fetch_time', mysql.DATETIME(), nullable=True))
    op.add_column('tab_actor', sa.Column('last_res_download_time', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_tab_actor_last_fetch_time'), table_name='tab_actor')
    op.create_index(op.f('ix_tab_actor_last_res_download_time'), 'tab_actor', ['last_res_download_time'], unique=False)
    op.create_index(op.f('ix_tab_actor_last_post_fetch_time'), 'tab_actor', ['last_post_fetch_time'], unique=False)
    op.drop_column('tab_actor', 'last_fetch_time')
    # ### end Alembic commands ###
