"""add index to sort

Revision ID: af32fb0f41f3
Revises: 73a5c745c822
Create Date: 2025-09-25 20:23:08.295981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af32fb0f41f3'
down_revision: Union[str, None] = '73a5c745c822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tab_actor_completed_post_count'), 'tab_actor', ['completed_post_count'], unique=False)
    op.create_index(op.f('ix_tab_actor_group_time'), 'tab_actor', ['group_time'], unique=False)
    op.create_index(op.f('ix_tab_actor_last_post_fetch_time'), 'tab_actor', ['last_post_fetch_time'], unique=False)
    op.create_index(op.f('ix_tab_actor_last_res_download_time'), 'tab_actor', ['last_res_download_time'], unique=False)
    op.create_index(op.f('ix_tab_actor_total_post_count'), 'tab_actor', ['total_post_count'], unique=False)
    op.create_index(op.f('ix_tab_actor_main_score'), 'tab_actor_main', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_actor_main_score'), table_name='tab_actor_main')
    op.drop_index(op.f('ix_tab_actor_total_post_count'), table_name='tab_actor')
    op.drop_index(op.f('ix_tab_actor_last_res_download_time'), table_name='tab_actor')
    op.drop_index(op.f('ix_tab_actor_last_post_fetch_time'), table_name='tab_actor')
    op.drop_index(op.f('ix_tab_actor_group_time'), table_name='tab_actor')
    op.drop_index(op.f('ix_tab_actor_completed_post_count'), table_name='tab_actor')
    # ### end Alembic commands ###
