"""remove folder order

Revision ID: b85b8e7a2758
Revises: fe0d0fde4cac
Create Date: 2025-08-09 00:12:37.586377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b85b8e7a2758'
down_revision: Union[str, None] = 'fe0d0fde4cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rel_actor_favorite', 'folder_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rel_actor_favorite', sa.Column('folder_order', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
