"""has remark

Revision ID: b9a87a00d3be
Revises: c065b3d85225
Create Date: 2025-05-21 14:28:22.752090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b9a87a00d3be'
down_revision: Union[str, None] = 'c065b3d85225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute("""
    UPDATE tab_actor_main SET has_remark = 1 WHERE remark IS NOT NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
