"""add flags to actor group model

Revision ID: ba8f1622e99e
Revises: d23a2eeaf078
Create Date: 2025-11-07 21:09:59.675949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8f1622e99e'
down_revision: Union[str, None] = 'd23a2eeaf078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor_group', sa.Column('flags', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
    # 基于 has_folder 和 is_initial 初始化 flags
    # EActorGroupFlag.HasFolder = 1
    # EActorGroupFlag.IsInitial = 1 << 1 = 2
    op.execute("""
        UPDATE tab_actor_group 
        SET flags = 
            CASE WHEN has_folder = 1 THEN 1 ELSE 0 END +
            CASE WHEN is_initial = 1 THEN 2 ELSE 0 END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_actor_group', 'flags')
    # ### end Alembic commands ###
