"""res width height duration

Revision ID: bb0f7750b8b5
Revises: 5fd22a46fcfe
Create Date: 2025-06-23 13:22:01.185703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0f7750b8b5'
down_revision: Union[str, None] = '5fd22a46fcfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_res', sa.Column('res_duration', sa.Integer(), nullable=False))
    op.add_column('tab_res', sa.Column('res_width', sa.Integer(), nullable=False))
    op.add_column('tab_res', sa.Column('res_height', sa.Integer(), nullable=False))
    op.create_index('idx_post_id_res_index', 'tab_res', ['post_id', 'res_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_id_res_index', table_name='tab_res')
    op.drop_column('tab_res', 'res_height')
    op.drop_column('tab_res', 'res_width')
    op.drop_column('tab_res', 'res_duration')
    # ### end Alembic commands ###
