"""add column has comment

Revision ID: c065b3d85225
Revises: 44a4ed2d4759
Create Date: 2025-05-21 13:42:34.325793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c065b3d85225'
down_revision: Union[str, None] = '44a4ed2d4759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_post', sa.Column('has_comment', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_tab_post_has_comment'), 'tab_post', ['has_comment'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
    UPDATE tab_post SET has_comment = 1 WHERE comment IS NOT NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_post_has_comment'), table_name='tab_post')
    op.drop_column('tab_post', 'has_comment')
    # ### end Alembic commands ###
