"""support long dm post id

Revision ID: c900895f4c2e
Revises: f78e2648c0e3
Create Date: 2025-10-31 18:52:28.090675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c900895f4c2e'
down_revision: Union[str, None] = 'f78e2648c0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_post', 'post_id_str',
                    existing_type=mysql.VARCHAR(length=20),
                    type_=sa.String(length=100),
                    existing_nullable=False)
    # ### end Alembic commands ###
    # 为 is_dm = true 的记录添加 DM 前缀（如果还没有前缀）
    op.execute("""
        UPDATE tab_post 
        SET post_id_str = CONCAT('DM', post_id_str)
        WHERE is_dm = 1 
          AND post_id_str NOT LIKE 'DM%';
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        UPDATE tab_post 
        SET post_id_str = SUBSTRING(post_id_str, 3)
        WHERE is_dm = 1 
          AND post_id_str LIKE 'DM%';
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_post', 'post_id_str',
                    existing_type=sa.String(length=100),
                    type_=mysql.VARCHAR(length=20),
                    existing_nullable=False)
    # ### end Alembic commands ###
    # 移除 DM 前缀（如果有的话）
