"""add icon_hash to actor

Revision ID: d3241805c36a
Revises: 082e939af522
Create Date: 2025-11-12 20:31:23.897706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3241805c36a'
down_revision: Union[str, None] = '082e939af522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('icon_hash', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_tab_actor_icon_hash'), 'tab_actor', ['icon_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_actor_icon_hash'), table_name='tab_actor')
    op.drop_column('tab_actor', 'icon_hash')
    # ### end Alembic commands ###
