"""remove popular rank, add favorite count to actor

Revision ID: dce9abcbb444
Revises: f1d259820651
Create Date: 2026-01-12 09:53:39.672572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dce9abcbb444'
down_revision: Union[str, None] = 'f1d259820651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('favorite_count', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tab_actor_popular_rank'), table_name='tab_actor')
    op.create_index(op.f('ix_tab_actor_favorite_count'), 'tab_actor', ['favorite_count'], unique=False)
    op.drop_column('tab_actor', 'popular_rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('popular_rank', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tab_actor_favorite_count'), table_name='tab_actor')
    op.create_index(op.f('ix_tab_actor_popular_rank'), 'tab_actor', ['popular_rank'], unique=False)
    op.drop_column('tab_actor', 'favorite_count')
    # ### end Alembic commands ###
