"""rename actor list to favorite folder

Revision ID: dfe549bedcd7
Revises: 98c2dbe36c5f
Create Date: 2025-07-18 15:40:58.797415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfe549bedcd7'
down_revision: Union[str, None] = '98c2dbe36c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_favorite_folder',
    sa.Column('folder_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_name', sa.String(length=30), nullable=False),
    sa.Column('folder_desc', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('folder_id'),
    sa.UniqueConstraint('folder_name')
    )
    op.create_table('rel_actor_favorite',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('folder_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['tab_actor.actor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['tab_favorite_folder.folder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'folder_id')
    )
    op.drop_table('rel_actor_list')
    op.drop_index('list_name', table_name='tab_actor_list')
    op.drop_table('tab_actor_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_actor_list',
    sa.Column('list_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('list_desc', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('list_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('list_name', 'tab_actor_list', ['list_name'], unique=True)
    op.create_table('rel_actor_list',
    sa.Column('actor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('list_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('list_order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['tab_actor.actor_id'], name='rel_actor_list_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['tab_actor_list.list_id'], name='rel_actor_list_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'list_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('rel_actor_favorite')
    op.drop_table('tab_favorite_folder')
    # ### end Alembic commands ###
