"""actor single comment

Revision ID: e0ef92b4431a
Revises: f7a3a3c3dbdf
Create Date: 2025-08-01 21:56:42.432647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ef92b4431a'
down_revision: Union[str, None] = 'f7a3a3c3dbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('comment', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_actor', 'comment')
    # ### end Alembic commands ###
