"""fix db

Revision ID: e2e6d183e9f1
Revises: 
Create Date: 2025-05-20 22:57:19.957773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2e6d183e9f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tab_log_ibfk_1', 'tab_log', type_='foreignkey')
    op.create_foreign_key(None, 'tab_log', 'tab_actor', ['actor_id'], ['actor_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tab_res_post_id'), 'tab_res', ['post_id'], unique=False)
    op.create_index(op.f('ix_tab_res_res_url_id'), 'tab_res', ['res_url_id'], unique=False)
    op.drop_constraint('tab_res_FK', 'tab_res', type_='foreignkey')
    op.create_foreign_key(None, 'tab_res', 'tab_res_url', ['res_url_id'], ['url_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tab_res', 'tab_post', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.alter_column('tab_res_url', 'hash_binary',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_res_url', 'hash_binary',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.drop_constraint(None, 'tab_res', type_='foreignkey')
    op.drop_constraint(None, 'tab_res', type_='foreignkey')
    op.create_foreign_key('tab_res_FK', 'tab_res', 'tab_post', ['post_id'], ['post_id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_index(op.f('ix_tab_res_res_url_id'), table_name='tab_res')
    op.drop_index(op.f('ix_tab_res_post_id'), table_name='tab_res')
    op.drop_constraint(None, 'tab_log', type_='foreignkey')
    op.create_foreign_key('tab_log_ibfk_1', 'tab_log', 'tab_actor', ['actor_id'], ['actor_id'])
    # ### end Alembic commands ###
