"""remove last post id

Revision ID: e42a60bfbb62
Revises: 0cd13cfa83fe
Create Date: 2026-03-29 21:14:43.677480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e42a60bfbb62'
down_revision: Union[str, None] = '0cd13cfa83fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_actor', 'last_post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('last_post_id', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
