"""add is_initial to avtor group model

Revision ID: e54ec08c6609
Revises: 719ec9e96a87
Create Date: 2025-10-10 21:27:15.884733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54ec08c6609'
down_revision: Union[str, None] = '719ec9e96a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor_group', sa.Column('is_initial', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_actor_group', 'is_initial')
    # ### end Alembic commands ###
