"""split res size

Revision ID: e9c4df1c277d
Revises: 94542a1beaf0
Create Date: 2025-06-29 21:06:58.535328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9c4df1c277d'
down_revision: Union[str, None] = '94542a1beaf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor_file_info', sa.Column('img_size', sa.BigInteger(), nullable=False))
    op.add_column('tab_actor_file_info', sa.Column('video_size', sa.BigInteger(), nullable=False))
    op.drop_column('tab_actor_file_info', 'res_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor_file_info', sa.Column('res_size', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('tab_actor_file_info', 'video_size')
    op.drop_column('tab_actor_file_info', 'img_size')
    # ### end Alembic commands ###
