"""add popular rank to actor

Revision ID: f1d259820651
Revises: ace9746fb9d8
Create Date: 2026-01-11 17:40:57.353822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d259820651'
down_revision: Union[str, None] = 'ace9746fb9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column('popular_rank', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tab_actor_popular_rank'), 'tab_actor', ['popular_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_actor_popular_rank'), table_name='tab_actor')
    op.drop_column('tab_actor', 'popular_rank')
    # ### end Alembic commands ###
