"""add last_fetch_time to post model

Revision ID: f78e2648c0e3
Revises: e54ec08c6609
Create Date: 2025-10-28 21:10:12.716170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78e2648c0e3'
down_revision: Union[str, None] = 'e54ec08c6609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tab_log_log_type'),
                    'tab_log', ['log_type'], unique=False)
    op.add_column('tab_post', sa.Column('last_fetch_time',
                  sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE tab_post p
        INNER JOIN tab_actor a ON p.actor_id = a.actor_id
        SET p.last_fetch_time = a.last_post_fetch_time
        WHERE p.completed = 1
        AND p.last_fetch_time IS NULL
        AND a.last_post_fetch_time IS NOT NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_post', 'last_fetch_time')
    op.drop_index(op.f('ix_tab_log_log_type'), table_name='tab_log')
    # ### end Alembic commands ###
