"""check 2

Revision ID: f7a3a3c3dbdf
Revises: dfe549bedcd7
Create Date: 2025-07-22 21:01:42.634373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7a3a3c3dbdf'
down_revision: Union[str, None] = 'dfe549bedcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_actor_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_actor_list',
    sa.Column('list_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('list_desc', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('list_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
