"""actor tag group

Revision ID: fe0d0fde4cac
Revises: e0ef92b4431a
Create Date: 2025-08-06 23:43:30.844308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0d0fde4cac'
down_revision: Union[str, None] = 'e0ef92b4431a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_actor_tag_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=30), nullable=False),
    sa.Column('group_desc', sa.String(length=100), nullable=True),
    sa.Column('group_priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.add_column('tab_actor_tag', sa.Column('tag_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tab_actor_tag', 'tab_actor_tag_group', ['tag_group_id'], ['group_id'], ondelete='SET NULL')
    op.add_column('tab_favorite_folder', sa.Column('folder_priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_favorite_folder', 'folder_priority')
    op.drop_constraint(None, 'tab_actor_tag', type_='foreignkey')
    op.drop_column('tab_actor_tag', 'tag_group_id')
    op.drop_table('tab_actor_tag_group')
    # ### end Alembic commands ###
