"""add current and completed post counts to actor

Revision ID: ff14adbcd044
Revises: b85b8e7a2758
Create Date: 2025-08-11 22:28:58.459645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff14adbcd044'
down_revision: Union[str, None] = 'b85b8e7a2758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_actor', sa.Column(
        'current_post_count', sa.Integer(), nullable=False))
    op.add_column('tab_actor', sa.Column(
        'completed_post_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###

    actor_table = sa.table('tab_actor',
                        sa.column('actor_id', sa.Integer),
                        sa.column('current_post_count', sa.Integer),
                        sa.column('completed_post_count', sa.Integer)
                        )
    post_table = sa.table('tab_post',
                       sa.column('actor_id', sa.Integer),
                       sa.column('completed', sa.Boolean)
                       )

    # 计算每个 actor 的总 post 数的子查询
    current_count_subquery = (
        sa.select(sa.func.count(post_table.c.actor_id))
        .where(post_table.c.actor_id == actor_table.c.actor_id)
        .scalar_subquery()
    )

    # 计算每个 actor 的已完成 post 数的子查询
    completed_count_subquery = (
        sa.select(sa.func.count(post_table.c.actor_id))
        .where(post_table.c.actor_id == actor_table.c.actor_id)
        .where(post_table.c.completed == True)
        .scalar_subquery()
    )

    # 构建并执行一个 UPDATE 语句，用子查询的结果来填充新列
    update_stmt = (
        sa.update(actor_table)
        .values(
            current_post_count=current_count_subquery,
            completed_post_count=completed_count_subquery
        )
    )

    # 获取 Alembic 当前的数据库连接并执行语句
    conn = op.get_bind()
    conn.execute(update_stmt)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_actor', 'completed_post_count')
    op.drop_column('tab_actor', 'current_post_count')
    # ### end Alembic commands ###
